[images]
  remote_images = [
    "https://ext.same-assets.com/3529001419/3184741937.jpeg",
    "https://ext.same-assets.com/1108925775/3482053257.jpeg",
    "https://ext.same-assets.com/25177141/2926772498.jpeg",
    "https://ext.same-assets.com/384657508/775680989.jpeg",
    "https://ext.same-assets.com/2500381268/3965457159.jpeg",
    "https://ext.same-assets.com/2444824034/3856998482.jpeg"
  ]

[build]
  command = "bun run build"
  publish = "dist"

[dev]
  command = "bun run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
